# Generated by Django 3.2.9 on 2022-02-20 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0002_resident_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Currentdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
