# Generated by Django 3.2.9 on 2022-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0003_resident_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Currentdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
