# Generated by Django 4.0.2 on 2022-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0004_alter_resident_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Age',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='Birthdate',
            field=models.DateField(verbose_name='Birthdate(YYYY/MM/DD)'),
        ),
    ]
