# Generated by Django 4.0.2 on 2022-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0005_resident_age_alter_resident_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='Currentdate',
        ),
        migrations.AlterField(
            model_name='resident',
            name='Birthdate',
            field=models.DateField(verbose_name='Birthdate(YYYY-MM-DD)'),
        ),
    ]
