# Generated by Django 4.0.2 on 2022-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0006_remove_resident_currentdate_alter_resident_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
