# Generated by Django 4.0.2 on 2022-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0008_alter_resident_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Address',
            field=models.TextField(max_length=250, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='Vaccination',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Non-Vaccinated', 'Non-Vaccinated')], max_length=100, verbose_name='Vaccination Status'),
        ),
    ]
