# Generated by Django 4.0.2 on 2022-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0010_alter_resident_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Birthdate',
            field=models.DateField(),
        ),
    ]
