# Generated by Django 4.0.2 on 2022-02-21 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0011_alter_resident_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
