# Generated by Django 3.2.9 on 2022-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0014_resident_created_date_resident_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Profile Picture'),
        ),
    ]
