# Generated by Django 3.2.9 on 2022-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0015_alter_resident_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
