# Generated by Django 4.0.2 on 2022-03-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0017_auto_20220228_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='Age',
        ),
    ]
