# Generated by Django 4.0.2 on 2022-04-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0020_official'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Official',
        ),
    ]
