# Generated by Django 4.0.2 on 2022-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0021_delete_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='pic',
            field=models.ImageField(blank=True, default='images/default_pp.jpg', null=True, upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
