# Generated by Django 4.0.2 on 2022-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0023_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='images/default_pp.jpg', null=True, upload_to='images/', verbose_name='Profile Picture')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not Specified', max_length=100)),
                ('Contact', models.CharField(max_length=11)),
                ('Marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], default='', max_length=100)),
                ('Citizenship', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Vaccination', models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Non-Vaccinated', 'Non-Vaccinated')], default='', max_length=100, verbose_name='Vaccination Status')),
                ('Address', models.TextField(max_length=250, verbose_name='Street Address')),
                ('Blacklisted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
