# Generated by Django 4.0.2 on 2022-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0025_tempresident_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempresident',
            name='Vaccination',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated')], default='', max_length=100, verbose_name='Vaccination Status'),
        ),
    ]
