# Generated by Django 4.0.2 on 2022-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0027_alter_resident_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Voluntary', 'Voluntary'), ('Senior', 'Senior'), ('Indigent', 'Indigent'), ('Sponsored', 'Sponsored'), ('Lifetime', 'Lifetime'), ('OFW', 'OFW'), ('Employed', 'Employed')], default='', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
        migrations.AddField(
            model_name='tempresident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Voluntary', 'Voluntary'), ('Senior', 'Senior'), ('Indigent', 'Indigent'), ('Sponsored', 'Sponsored'), ('Lifetime', 'Lifetime'), ('OFW', 'OFW'), ('Employed', 'Employed')], default='', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
    ]
