# Generated by Django 4.0.2 on 2022-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0028_resident_philhealth_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Voluntary', 'Voluntary'), ('Employed', 'Employed'), ('Senior', 'Senior'), ('Sponsored', 'Sponsored'), ('Lifetime', 'Lifetime'), ('Indigent', 'Indigent'), ('OFW', 'OFW')], default='', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Voluntary', 'Voluntary'), ('None', 'None'), ('Employed', 'Employed'), ('Senior', 'Senior'), ('Sponsored', 'Sponsored'), ('Lifetime', 'Lifetime'), ('Indigent', 'Indigent'), ('OFW', 'OFW')], default='None', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
    ]
