# Generated by Django 4.0.2 on 2022-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0029_alter_resident_philhealth_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Senior', 'Senior'), ('Voluntary', 'Voluntary'), ('Lifetime', 'Lifetime'), ('Indigent', 'Indigent'), ('OFW', 'OFW'), ('Sponsored', 'Sponsored')], default='None', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Senior', 'Senior'), ('None', 'None'), ('Voluntary', 'Voluntary'), ('Lifetime', 'Lifetime'), ('Indigent', 'Indigent'), ('OFW', 'OFW'), ('Sponsored', 'Sponsored')], default='None', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
    ]
