# Generated by Django 4.0.2 on 2022-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0032_alter_resident_philhealth_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('None', 'None'), ('Employed', 'Employed'), ('Voluntary', 'Voluntary'), ('OFW', 'OFW'), ('Sponsored', 'Sponsored'), ('Indigent', 'Indigent'), ('Lifetime', 'Lifetime'), ('Senior', 'Senior')], default='None', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Philhealth_membership',
            field=models.CharField(choices=[('None', 'None'), ('Employed', 'Employed'), ('Voluntary', 'Voluntary'), ('OFW', 'OFW'), ('Sponsored', 'Sponsored'), ('Indigent', 'Indigent'), ('Lifetime', 'Lifetime'), ('Senior', 'Senior')], default='None', max_length=100, verbose_name='Philhealth Membership Type'),
        ),
    ]
