# Generated by Django 4.0.2 on 2022-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0035_alter_resident_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
