# Generated by Django 4.0.2 on 2022-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0036_resident_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Resident_code',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='Address',
            field=models.CharField(max_length=250, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Address',
            field=models.CharField(max_length=250, verbose_name='Street Address'),
        ),
    ]
