# Generated by Django 4.0.2 on 2022-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0037_resident_resident_code_alter_resident_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
