# Generated by Django 4.0.2 on 2022-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0038_alter_resident_email_alter_resident_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempresident',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
