# Generated by Django 4.0.2 on 2022-04-30 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0039_alter_tempresident_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')]),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')]),
        ),
    ]
