# Generated by Django 4.0.2 on 2022-05-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0040_alter_resident_contact_alter_tempresident_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='Resident.resident')),
                ('Member', models.ManyToManyField(related_name='mem', to='Resident.Resident')),
            ],
        ),
    ]
