# Generated by Django 4.0.2 on 2022-05-18 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0040_alter_resident_contact_alter_tempresident_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseholdName', models.CharField(max_length=250)),
                ('Contact', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')], verbose_name='Telephone/Mobile')),
                ('Homeowner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('Income', models.CharField(choices=[('131,000 and up', '131,000 and up'), ('41,000 - 130,000', '41,000 - 130,000'), ('11,000 - 40,000', '11,000 - 40,000'), ('Less than 10,000', 'Less than 10,000')], default='', max_length=250)),
                ('Head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident', verbose_name='Head of Household')),
                ('Member', models.ManyToManyField(related_name='mem', to='Resident.Resident', verbose_name='Household Members')),
            ],
        ),
    ]
