# Generated by Django 4.0.2 on 2022-05-18 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0040_alter_resident_contact_alter_tempresident_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseholdName', models.CharField(blank=True, max_length=250, null=True)),
                ('Contact', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')], verbose_name='Telephone/Mobile')),
                ('Homeowner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('Members', models.ManyToManyField(to='Resident.Resident')),
            ],
        ),
    ]
