# Generated by Django 4.0.2 on 2022-05-18 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0041_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Contact',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')], verbose_name='Telephone/Mobile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='Homeowner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='HouseholdName',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Citizenship',
            field=models.CharField(max_length=100, verbose_name='Ethnicity'),
        ),
    ]
