# Generated by Django 4.0.2 on 2022-05-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0041_alter_resident_citizenship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='household',
            name='Members',
            field=models.ManyToManyField(through='Resident.Members', to='Resident.Resident'),
        ),
        migrations.AddField(
            model_name='members',
            name='Head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.household'),
        ),
        migrations.AddField(
            model_name='members',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident'),
        ),
    ]
