# Generated by Django 4.0.2 on 2022-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0041_alter_resident_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='Member',
            field=models.ManyToManyField(related_name='mem', to='Resident.Resident', verbose_name='Household Memsssbers'),
        ),
    ]
