# Generated by Django 4.0.2 on 2022-05-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0042_members_alter_household_members_members_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Head',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='head', to='Resident.resident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='Members',
            field=models.ManyToManyField(to='Resident.Resident'),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
