# Generated by Django 4.0.2 on 2022-05-18 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0043_household_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='Contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only numbers are accepted')], verbose_name='Telephone/Mobile'),
        ),
        migrations.AlterField(
            model_name='household',
            name='Head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident', verbose_name='Head of Household'),
        ),
        migrations.AlterField(
            model_name='household',
            name='Member',
            field=models.ManyToManyField(related_name='mem', to='Resident.Resident', verbose_name='Household Members'),
        ),
    ]
