# Generated by Django 4.0.2 on 2022-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0043_household_head_alter_household_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='Members',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='household',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='household',
            name='Homeowner',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HouseholdName',
        ),
        migrations.AlterField(
            model_name='resident',
            name='Citizenship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tempresident',
            name='Citizenship',
            field=models.CharField(max_length=100),
        ),
    ]
