# Generated by Django 4.0.2 on 2022-05-19 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0043_alter_household_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Established'),
            preserve_default=False,
        ),
    ]
