# Generated by Django 4.0.2 on 2022-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0044_household_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Number',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
