# Generated by Django 4.0.2 on 2022-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0044_rename_members_household_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='Member',
        ),
        migrations.AddField(
            model_name='household',
            name='Members',
            field=models.ManyToManyField(to='Resident.Resident'),
        ),
    ]
