# Generated by Django 4.0.2 on 2022-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0045_household_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='House Address'),
        ),
    ]
