# Generated by Django 4.0.2 on 2022-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0046_household_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempresident',
            name='identification',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Identification Card'),
            preserve_default=False,
        ),
    ]
