# Generated by Django 4.0.2 on 2022-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0046_remove_household_members_household_hmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Members',
            field=models.ManyToManyField(to='Resident.Resident'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HMembers',
            field=models.ManyToManyField(related_name='mem', to='Resident.Resident'),
        ),
    ]
