# Generated by Django 3.2.9 on 2022-02-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resident', '0016_alter_resident_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blotreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complainant', models.CharField(max_length=50)),
                ('Complaint', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Offender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resident.resident')),
            ],
        ),
    ]
