# Generated by Django 4.0.2 on 2022-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0035_alter_resident_marital_status'),
        ('Blotter', '0002_alter_blotreport_offender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotreport',
            name='Facts',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blotreport',
            name='Offender_unregistered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blotreport',
            name='Offender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resident.resident'),
        ),
    ]
