# Generated by Django 4.0.2 on 2022-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter', '0003_blotreport_facts_blotreport_offender_unregistered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotreport',
            name='Unregistered',
            field=models.BooleanField(default=False),
        ),
    ]
