# Generated by Django 4.0.2 on 2022-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter', '0006_remove_blotreport_evidences_evidences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blotreport',
            name='Complaint',
            field=models.TextField(max_length=1000),
        ),
    ]
