# Generated by Django 4.0.2 on 2022-04-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officials',
        ),
    ]
