# Generated by Django 4.0.2 on 2022-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Certification', '0002_delete_officials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
