# Generated by Django 4.0.2 on 2022-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certrequest',
            name='Purpose',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certrequest',
            name='Request_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
