# Generated by Django 4.0.2 on 2022-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0004_certrequest_purpose_certrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certrequest',
            name='Email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
