# Generated by Django 4.0.2 on 2022-04-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0005_certrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certrequest',
            name='Resident_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
