# Generated by Django 4.0.2 on 2022-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0007_certrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certrequest',
            name='Request_type',
            field=models.CharField(choices=[('Barangay Certificate', 'Barangay Certificate'), ('Certificate of Indigency', 'Certificate of Indigency')], default='', max_length=100),
        ),
    ]
