# Generated by Django 4.0.2 on 2022-04-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0008_alter_certrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certrequest',
            name='Resident_code',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
