# Generated by Django 4.0.2 on 2022-05-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0009_certrequest_resident_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certrequest',
            name='Requestcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
