# Generated by Django 4.0.2 on 2022-05-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0010_certrequest_requestcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requestcode', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
