# Generated by Django 4.0.2 on 2022-04-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_officialz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officialz',
        ),
    ]
