# Generated by Django 4.0.2 on 2022-04-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_delete_officialz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officials',
            new_name='Official',
        ),
    ]
