# Generated by Django 4.0.2 on 2022-04-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_officials_official'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Official',
        ),
    ]
