# Generated by Django 4.0.2 on 2022-04-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='First_name',
            new_name='Baranagay_Secretary',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='Last_name',
            new_name='Baranagay_Treasurer',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='Middle_name',
            new_name='Barangay_Chairman',
        ),
        migrations.AddField(
            model_name='official',
            name='SK_Chairman',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
