# Generated by Django 4.0.2 on 2022-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_rename_first_name_official_baranagay_secretary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='Baranagay_Secretary',
            new_name='Barangay_Secretary',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='Baranagay_Treasurer',
            new_name='Barangay_Treasurer',
        ),
    ]
