# Generated by Django 4.0.2 on 2022-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_baranagay_secretary_official_barangay_secretary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='Barangay_Councilors',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='SK_Councilors',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
